// import { useEffect, useState } from 'react'
// import Auth from '../components/Auth'
// import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
// import AI_Generate from './generate'

// import SpotifyWebApi from 'spotify-web-api-node'


// export default function Home() {
//   const router = useRouter()
//   const q = router.query

//   return (
//     <div className={styles.container}>
//       {
//         q.code !== undefined ? <AI_Generate authCode={q.code} spotifyApi={spotifyApi}/> : <Auth routerPush={spotifyApi.createAuthorizeURL(scopes)}/>
//       }
//     </div>
//   )
// }



import Head from 'next/head'
import Link from "next/link"
import styles from '../styles/Home.module.css'
import { useEffect } from 'react';
export default function Home({ genres }) {
  const router = useRouter();

  // useEffect(() => {
  //   router.push('http://localhost:3000/login')
  // }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Music Recommender</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Music Recommender</h1>
        <h2>Recommended Artists</h2>
      </main>
      <aside>
        <h2>Genre List</h2>
        {/* <ul>
          {genres.map(genre => 
          <li key={genre}>
            <Link href={`/${genre}`}>
              <a>{genre}</a>
            </Link>
          </li>)}
        </ul> */}
      </aside> 
      {/* <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

// export async function getStaticProps() {

//   const data = await fetch("https://api.spotify.com/v1/recommendations/available-genre-seeds", 
//   {
//     headers:{
//       Authorization: `Bearer ${process.env.CLIENT_ID}`
//     }
//   }).then(response => response.json());

//   console.log(data);

//   return {
//     props: {
//       genres: ['ex1', 'ex2']
//     },

//   }
// }